@host= http://localhost:5007

POST {{host}}/auth/register
Content-Type: application/json


{
	"firstName": "Sudip",
	"lastName": "Parajuli",
	"email": "sudipparajuli06@gmial.com",
	"password": "Sudip1234"
}
